### ISSUE TITLE
Crash while diggin down

### ISSUE THREAD

**Issue by zEpiixz** [MaxNeedsSnacks/roadrunner#30] opened 2021-11-04 14:10 UTC
Im sorry if that might be a duplicate, but im not very good  with  reading that.

https://pastebin.com/30bEGQCm

**Comment by MaxNeedsSnacks** [comment] 2021-11-04 15:03
This *is* a duplicate of #12, but since I basically haven't been able to find **any** real leads on this, do you mind sending us your world download over Discord or something? People have said that this crash basically soft-bricked their world until they removed RoadRunner, and if that is the case for you as well, I hope that your save could maybe give us some insight into **why** it keeps crashing

**Comment by MaxNeedsSnacks** [comment] 2021-11-13 10:52
Merging this into #12, if you have any more information regarding this please comment it over there ^^

**Closed as completed by MaxNeedsSnacks** 2021-11-13 10:52 UTC
