### ISSUE TITLE
Crash With Project Vibrant Journeys

### ISSUE THREAD

**Issue by BlackRoosterTrapHouse** [MaxNeedsSnacks/roadrunner#43] opened 2021-12-11 17:14 UTC
Crashes with Project Vibrant Journeys

[debug.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7697458/debug.log)
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7697459/latest.log)

Updated Links

**Comment by malte0811** [comment] 2021-12-11 17:23
Those logs don't have RoadRunner installed, and no obvious crash either. Can you provide the correct logs?

**Comment by BlackRoosterTrapHouse** [comment] 2021-12-11 17:28
> Those logs don't have RoadRunner installed, and no obvious crash either. Can you provide the correct logs?

Apologies. Updated links. When clicking play on launcher, it crashes with Exit Code 0. I've narrowed it down to PVJ and RoadRunner (though I do have other mods installed)

**Comment by MaxNeedsSnacks** [comment] 2022-01-02 13:09
Those links still don't imply any sort of crash, they only show you entering the world and the log is muddied up by *quite* a lot of other mods. If you can narrow it down to just RoadRunner and PVJ, can you try reproducing this in an instance with only those two installed?

**Comment by MaxNeedsSnacks** [comment] 2022-03-07 17:29
Gonna be closing this issue for now since we don't have enough information to go by here, unfortunately. Feel free to reopen if this still occurs in the future ^^

**Closed as completed by MaxNeedsSnacks** 2022-03-07 17:29 UTC
