### ISSUE TITLE
[1.16.5 v1.4] Crash with Create

### ISSUE THREAD

**Issue by Elfinlocks** [MaxNeedsSnacks/roadrunner#47] opened 2021-12-27 18:44 UTC
### Reproduction Steps
I'm encountering this issue with my modpack, Astral Engineering, but should be possible to replicate via simply installing Create and RoadRunner on their latest versions. 

https://www.curseforge.com/minecraft/modpacks/astral-engineering/files/3578307

When using Create's pondering system, the game crashed out, citing a rendering error. Removing the RoadRunner mod allows everything to function without issue. 

### Crash Report File
[crash-2021-12-27_09.11.43-client.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7781385/crash-2021-12-27_09.11.43-client.txt)

### Additional Information
Here's a link to the Crashy info as well: https://crashy.net/G0nMWJxX5TgG0yeqcKhf

**Comment by MaxNeedsSnacks** [comment] 2022-01-03 11:52
Can you try reproducing this with **just** Create and RoadRunner? The log mentions other mods like the TARDIS mod as well and I want to keep potential error sources to a minimum

**Comment by malte0811** [comment] 2022-01-08 14:10
This looks like a general issue between Create and TARDIS, though it may not be possible to actually trigger it with just those two. Create creates [chunks with `null` worlds](https://github.com/Creators-of-Create/Create/blob/dfe2f41b59d91bd9bbf11fb6bca7b260dc1c47fe/src/main/java/com/simibubi/create/foundation/utility/worldWrappers/chunk/EmptierChunk.java#L23), and TARDIS makes the (reasonable) assumption that chunks always have a world attached to them ([1](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/f92e0136d693f451b42f5c64f1cc6312cf4c8407/src/main/java/net/tardis/mod/events/CommonEvents.java#L237), [2](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/f92e0136d693f451b42f5c64f1cc6312cf4c8407/src/main/java/net/tardis/mod/helper/WorldHelper.java#L323)).

**Comment by 50ap5ud5** [comment] 2022-01-31 19:43
> This looks like a general issue between Create and TARDIS, though it may not be possible to actually trigger it with just those two. Create creates [chunks with `null` worlds](https://github.com/Creators-of-Create/Create/blob/dfe2f41b59d91bd9bbf11fb6bca7b260dc1c47fe/src/main/java/com/simibubi/create/foundation/utility/worldWrappers/chunk/EmptierChunk.java#L23), and TARDIS makes the (reasonable) assumption that chunks always have a world attached to them ([1](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/f92e0136d693f451b42f5c64f1cc6312cf4c8407/src/main/java/net/tardis/mod/events/CommonEvents.java#L237), [2](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/f92e0136d693f451b42f5c64f1cc6312cf4c8407/src/main/java/net/tardis/mod/helper/WorldHelper.java#L323)).

Hello, Tardis Mod developer here. You're right, Create does appear to be doing an unorthodox approach by not attaching a world to their custom Chunk.

From videos involving Create, many other mods that attach capabilities to all Chunks also face this compatibility crash issue with Create.

I have contacted the main developer of Create and from their response it wasn't so clear as to why they did this, just that they had no immediate need to attach a world to their chunk. 

A quick fix on a mod developer's side would be to do a null check before attaching capabilites. However, I'm not sure if Create will fix it on their end unless there are enough issue reports that highlight this issue, since their 1.16 versions are no longer being actively updated.

![Screenshot_20220201_071254](https://user-images.githubusercontent.com/22887654/151865794-5395517b-d186-40ce-a74b-35c13bf420eb.jpg)

**Comment by MaxNeedsSnacks** [comment] 2022-03-07 17:28
Gonna be closing this issue since this isn't a RoadRunner issue, but thanks for the insights nonetheless ^^

**Closed as completed by MaxNeedsSnacks** 2022-03-07 17:28 UTC
