### ISSUE TITLE
Crash with Chunk-Pregenerator

### ISSUE THREAD

**Issue by txnitxnichopper** [MaxNeedsSnacks/roadrunner#21] opened 2021-10-28 08:20 UTC
### Reproduction Steps
Random crash when using Chunk-Pregenerator, coming from a Lithium mixin.

### Crash Report File
[crash-2021-10-28_04.15.47-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7432412/crash-2021-10-28_04.15.47-server.txt)

**Comment by MaxNeedsSnacks** [comment] 2021-10-28 13:56
The issue seems to be in L92 here, I'm guessing something's trying to get POIs in a chunk before it's been fully loaded and because Lithium tries to get the entire Chunk at once rather than looking at individual subchunks, it crashes:

https://github.com/MaxNeedsSnacks/roadrunner/blob/b86456fbcf4626e177e1b90eb2a2a14303a9a725/src/main/java/me/jellysquid/mods/lithium/mixin/ai/poi/fast_retrieval/SerializingRegionBasedStorageMixin.java#L91-L94

The fix for this should be as simple as just safeguarding against null values, but for some reason Chunk Pregen doesn't wanna work in my userdev instance (it's just stuck on "Preparing" forever), so if you could test this commit in your pack that'd be awesome

**Comment by MaxNeedsSnacks** [comment] 2021-10-28 14:04
Artifacts for this build can be found [here](https://github.com/MaxNeedsSnacks/roadrunner/actions/runs/1394918454), be sure to use the **non-dev** jar when testing. I'll also test this just to make sure I haven't accidentally caused unintended side effects elsewhere

**Comment by Speiger** [comment] 2021-11-16 17:01
@MaxNeedsSnacks we kinda have a modcollision here...
ChunkPregen actually replaces your "loadedElements" when a pregeneration is started.
Because i am adding safety systems into place to make sure only the least used POIs are getting deleted.

If you could change your listeningLong2ObjectMap to one that is always putting the inserted element at the last slot (for both your Maps (loadedElements, columns))
then I could easily detect your mod and disable the replacement logic if it was detected and just manage the cleanup automatically for you.

Because right now you are feeding Mojangs Memory Leak and not allowing for a large world even if it is only a small amount that just will grow quite a lot faster.

**Comment by Speiger** [comment] 2021-11-16 17:10
To give the code that i am actually replacing your "loadedElements" with.
```java
public class Long2ObjectCustomMap<V> extends Long2ObjectLinkedOpenHashMap<V>
{
	private static final long serialVersionUID = -1320734769598019239L;
	
	public Long2ObjectCustomMap(Map<? extends Long, ? extends V> m)
	{
		super(m);
	}
	
	@Override
	public V put(long k, V v)
	{
		return putAndMoveToLast(k, v);
	}
	
	@Override
	public V get(long k)
	{
		return getAndMoveToLast(k);
	}
}
```
Chunk Pregen always keeps the last 50k used elements in there otherwise it is fighting with vanilla over what should stay loaded and what not and that seems to be the perfect ratio with pregeneration...
This just makes sure i always remove the least used 50k elements when it is time delete things...

**Comment by Speiger** [comment] 2021-11-16 17:32
@jellysquid3 sry for the ping.
But this might interests you too. Because this problem will arise too if I decide to port ChunkPregen to Fabric.
And I don't want to cause a Incompatibly with Lithium at all... I rather work together and only ask for this small change.
That would help reduce future issues.

(Just read a bit back)

**Comment by Speiger** [comment] 2021-11-23 00:45
@MaxNeedsSnacks update on the patch from my side. I am testing right now with 1.3
It is crashing once the memory Leak fix is applied which causes crashes on your side. Intentionally i might ask.
Might be JelliSquids intention to throw warning errors.

Anyways: The fix you need to do is implement this function. 
https://github.com/MaxNeedsSnacks/roadrunner/blob/1.16.x/forge/src/main/java/me/jellysquid/mods/lithium/mixin/ai/poi/fast_retrieval/SerializingRegionBasedStorageMixin.java#L52
Like expect it to be called. And also to cleanup your memory when it is called so no memory leak stays.

I implemented everything that is necessary from my side it make it work. Now the ball is on your side.
I am going to upload my patch hopefully tonight or tomorrow.

**Comment by Speiger** [comment] 2021-11-23 01:30
Ok my side of the patch is out. Here you can test with it.
https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator/files/3534451

**Closed as completed** 2021-11-28 09:03 UTC

**Comment by Speiger** [comment] 2021-12-01 11:03
Could you open this issue until it is confirmed to be fixed?
Since there is no testjar we cant confirm it.

**Comment by Speiger** [comment] 2022-05-03 12:20
For everyone reading through this this is fixed on both sides.
