### ISSUE TITLE
Crash using Chunk Pregenerator

### ISSUE THREAD

**Issue by Reshy** [MaxNeedsSnacks/roadrunner#33] opened 2021-11-09 07:10 UTC
### Reproduction Steps
Running Chunk Pre-generator and Blue Skies with the Roadrunner plugin.

### Crash Report File
[crash-2021-11-08_23.07.47-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7502682/crash-2021-11-08_23.07.47-server.txt)

**Comment by MaxNeedsSnacks** [comment] 2021-11-09 12:59
Probably a duplicate of #21, but since the OP of that hasn't replied so far, could you try and see whether the latest pre-release fixes this (and hopefully doesn't cause any other issues)? It should be up on GitHub in a minute or two

**Comment by MaxNeedsSnacks** [comment] 2021-11-13 10:52
Merging this into #21, if you have any more information regarding this please comment it over there ^^

**Closed as completed by MaxNeedsSnacks** 2021-11-13 10:52 UTC
