### ISSUE TITLE
[1.16.5] Incompatibility with FuturePack mod

### ISSUE THREAD

**Issue by Lgmrszd** [MaxNeedsSnacks/roadrunner#35] opened 2021-11-14 01:27 UTC
### Expected Behavior
In the mod [FuturePack](https://www.curseforge.com/minecraft/mc-mods/futurepack), there is Research Tree interface that you can open using item called Scanner. When you open it, Research Tree with different tabs and researches is displayed

### Actual Behavior
Opening this interface show only one tab icon, while producing errors in the game log (see screenshot in attachments)

### Reproduction Steps
1. Install RoadRunned and FuturePack (versions listed below)
2. `/give @p futurepack:escanner`
3. Open Scanner, click on a "Tech Tree" button (yellow one)

### Additional info
Issue in FuturePack repo: https://github.com/mcenderdragon/Futurepack-API/issues/831

Versions:
Minecraft: 1.16.5
Forge: 36.2.8
Futurepack: 1.16.5-31.2.6976
RoadRunner: mc1.16.5-1.3.0

### Attachments
Error from the logs: https://gist.github.com/Lgmrszd/90a6e7a6a9ff4551006bf4c72cd81718
Bugged Research Tree:
![screen1](https://user-images.githubusercontent.com/16291541/141663938-036ca95d-c0c2-4aaa-9b96-fa3638b746b9.png)
How Research Tree normally looks:
![screen2](https://user-images.githubusercontent.com/16291541/141663940-e4eb4160-51f4-4e99-b5de-1d502bffb60b.png)

**Comment by mcenderdragon** [comment] 2021-11-22 08:44
https://github.com/mcenderdragon/Futurepack-API/issues/831

Problem is cuased by these lines:

```
private void addInPogressReaserches(ServerWorld serv, ArrayList<Integer> inProg)
	{
		for(int i=0;i<serv.blockEntityList.size();i++)
		{	
			TileEntity tile = serv.blockEntityList.get(i); //Needs to be a indexed for loop to prevent concurennt modification exeption
			//and the get crashes.
```

What is the alternative to this that is compatible with RoadRunner ?

**Comment by MaxNeedsSnacks** [comment] 2022-05-26 18:31
The issue is that as far as I can tell, Futurepack mod is accessing the world / block entity list **off-thread**, which is usually an absolute no-go within Minecraft code (which is also why you're getting CMEs when doing it with a regular non-indexed foreach). RoadRunner has to work around some issues here as well because there are other mods performing off-thread modifications (off-thread *reads* should __usually__ be fine, but our hacks seem to break that in some cases), so I honestly don't know whose ""fault"" it is in this case.

Still, you should be able to disable the mixin within RoadRunner that causes this breakage (that would be `mixin.world.block_entity_ticking.collections`), though keep in mind that this will obviously incur a performance penalty.

Unfortunately, since neither I nor my co-maintainer have particularly much time to work on this mod right now, and support for 1.16 modded is winding down anyways, I doubt this is going to be fixed on our end, though, so I'll close this issue for the time being.

**Closed as not planned by MaxNeedsSnacks** 2022-05-26 18:31 UTC
Labels: wontfix, mod interaction
