### ISSUE TITLE
[1.16] Mixin apply failed roadrunner.mixins.json

### ISSUE THREAD

**Issue by ghost** [MaxNeedsSnacks/roadrunner#76] opened 2022-11-15 22:17 UTC
Once I'm in the Forge loading screen after 10-to-20 seconds the game crashes immediately.
This only happens when I have Roadrunner installed so maybe it could be a mod incompatibly issue.

### Crash Report File
Crash-Report-file | It didn't create one.
Log-file | [latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/10016514/latest.log)

### Additional Information
I'm using version 1.4.1 from [Curseforge](https://www.curseforge.com/minecraft/mc-mods/roadrunner/files/3683120).

**Comment by MaxNeedsSnacks** [comment] 2022-11-15 23:04
Duplicate of #56 / #2, RoadRunner is not compatible with Performant

**Closed as not planned by MaxNeedsSnacks** 2022-11-15 23:04 UTC
Labels: duplicate
