### ISSUE TITLE
Placing BuddyCards card display crashes when RoadRunner is present

### ISSUE THREAD

**Issue by jinkhya** [MaxNeedsSnacks/roadrunner#48] opened 2021-12-28 21:25 UTC
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.
1. Make a modpack with roadrunner 1.4.0 and buddycards 2.5.3
2. place a card display (wood type is irrelevant)
3. insta crash :)

Please mention why you think Meep Meep! may be the cause of the crash. If possible, please confirm that the crash does not happen when Meep Meep! is not installed.

I did check if Buddycard was crashing on its own but it only does if MeepMeep! is around !

### Crash Report File
https://gist.github.com/jinkhya/c3e2ca2906de77014709c41bb6bbe8fe

Thanks in advance :D

**Comment by MaxNeedsSnacks** [comment] 2022-01-02 13:15
Duplicate of #38, I unfortunately haven't really had the time to look into this yet :/

**Closed as completed by MaxNeedsSnacks** 2022-01-02 13:15 UTC
